development: 
  bin_path: /usr/local/coreseek/bin
  mem_limit: 128M
  charset_type: zh_cn.utf-8
  charset_dictpath: <%=RAILS_ROOT+"/dict"%> 
  pid_file: "/tmp/searchd.development.pid"       
  stopwords: <%=RAILS_ROOT+"/dict/stopwords_en.txt"%>     <%=RAILS_ROOT+"/dict/stopwords_zh_cn.txt"%>                  
  ngram_len: 0
test:  
  bin_path: /usr/local/coreseek/bin
  charset_type: zh_cn.utf-8
  charset_dictpath: <%=RAILS_ROOT+"/dict"%> 
  pid_file: "/tmp/searchd.test.pid"    
  stopwords: <%=RAILS_ROOT+"/dict/stopwords_en.txt"%>     <%=RAILS_ROOT+"/dict/stopwords_zh_cn.txt"%>               
  ngram_len: 0 
production:  
  bin_path: /usr/local/coreseek/bin
  charset_type: zh_cn.utf-8
  charset_dictpath: <%=RAILS_ROOT+"/dict"%> 
  pid_file: "/tmp/searchd.production.pid"    
  stopwords: <%=RAILS_ROOT+"/dict/stopwords_en.txt"%>     <%=RAILS_ROOT+"/dict/stopwords_zh_cn.txt"%>               
  ngram_len: 0
 
